version: '3'
services:
  web:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - "./server/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./server/config/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - "./server:/var/www/html"
    ports:
      - "8000:80"
    environment:
      - NGINX_HOST=localhost
    restart: unless-stopped
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: php
    restart: unless-stopped
    volumes:
      - "./server:/var/www/html"

  composer:
    image: "composer"
    volumes:
      - "./server:/app"
    command: install

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "9000:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.30
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=calendar
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - "3306:3306"
    volumes:
      - "./server/config/mysql/init-sql-scripts:/docker-entrypoint-initdb.d/:rw"
      - "./server/data/db/mysql:/var/lib/mysql"

  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    container_name: node
    restart: unless-stopped
    volumes:
      - "./client:/usr/src"
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true