version: '3'
services:
  web:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./config/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - ".:/var/www/html"
    ports:
      - "8000:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '\$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: unless-stopped
    depends_on:
      - php
      - mysql

  php:
    image: php:7.4-fpm-alpine
    container_name: php
    restart: unless-stopped
    volumes:
      - ".:/var/www/html"

  composer:
    image: "composer"
    volumes:
      - ".:/app"
    command: install

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.30
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"